// <auto-generated />
using System;
using GeziRehberi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeziRehberi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260310115121_FixSeed")]
    partial class FixSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("GeziRehberi.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BudgetRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HowToGetThere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeatherSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatToEat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BudgetRange = "Orta",
                            Category = "Tarih, Kültür",
                            Country = "Turkey",
                            Description = "Kıtaların buluştuğu nokta, eşsiz camileri, sarayları ve boğazı ile tarihi ve modern dokuyu bir araya getiriyor.",
                            HowToGetThere = "İstanbul Havalimanı (IST) veya Sabiha Gökçen (SAW) üzerinden ulaşabilirsiniz.",
                            ImageUrl = "https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&q=80&w=2000",
                            Latitude = 41.008200000000002,
                            Longitude = 28.978400000000001,
                            Name = "Istanbul",
                            WeatherSummary = "Yazlar sıcak ve nemli, kışlar ise soğuk, yağışlı ve bazen karlı geçer. Bahar ayları gezmek için en ideal zamandır.",
                            WhatToEat = "İskender Kebap, Simit, Boğaz kenarında Balık-Ekmek, Türk Kahvesi, Baklava."
                        },
                        new
                        {
                            Id = 2,
                            BudgetRange = "Yüksek",
                            Category = "Sanat, Romantizm",
                            Country = "France",
                            Description = "Aşıklar şehri, modanın, sanatın ve kültürün başkenti. Işıklar Şehri olarak da bilinir.",
                            HowToGetThere = "Charles de Gaulle Havalimanı (CDG) veya Orly Havalimanı (ORY) kullanarak merkeze ulaşabilirsiniz.",
                            ImageUrl = "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&q=80&w=2000",
                            Latitude = 48.8566,
                            Longitude = 2.3521999999999998,
                            Name = "Paris",
                            WeatherSummary = "Ilıman bir okyanus iklimi görülür. Bahar ve yaz ayları turizm açısından en popüler ve keyifli zamanlarıdır.",
                            WhatToEat = "Kruvasan, Makaron, Soğan Çorbası, Ratatouille, Salyangoz (Escargot)."
                        },
                        new
                        {
                            Id = 3,
                            BudgetRange = "Yüksek",
                            Category = "Teknoloji, Gelenek",
                            Country = "Japan",
                            Description = "Geleneksel tapınakların modern gökdelenlerle uyum içinde olduğu teknoloji ve kültür şehri.",
                            HowToGetThere = "Narita Uluslararası Havalimanı veya Haneda Havalimanı (merkeze daha yakın) üzerinden ulaşabilirsiniz.",
                            ImageUrl = "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&q=80&w=2000",
                            Latitude = 35.676200000000001,
                            Longitude = 139.65029999999999,
                            Name = "Tokyo",
                            WeatherSummary = "Temmuz ve Ağustos çok sıcak ve nemli olabilir. İlkbahar (Kiraz çiçekleri dönemi) ve Sonbahar en popüler ziyaret zamanlarıdır.",
                            WhatToEat = "Sushi, Ramen, Tempura, Takoyaki, Matcha tatlıları."
                        });
                });

            modelBuilder.Entity("GeziRehberi.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BudgetLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BudgetLevel = "Düşük",
                            CityId = 1,
                            Description = "Dünya mimarlık tarihinin günümüze kadar ayakta kalmış en önemli anıtları arasında yer alan Ayasofya.",
                            ImageUrl = "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&q=80&w=800",
                            Name = "Ayasofya",
                            Type = "Tarihi"
                        },
                        new
                        {
                            Id = 2,
                            BudgetLevel = "Orta",
                            CityId = 1,
                            Description = "Dünyanın en eski ve en büyük kapalı çarşılarından biri.",
                            ImageUrl = "https://images.unsplash.com/photo-1555541604-0618055eeefe?auto=format&fit=crop&q=80&w=800",
                            Name = "Kapalıçarşı",
                            Type = "Alışveriş"
                        },
                        new
                        {
                            Id = 3,
                            BudgetLevel = "Orta",
                            CityId = 2,
                            Description = "Paris'in sembolü ve en ikonik yapısı. Muhteşem bir manzara sunar.",
                            ImageUrl = "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&q=80&w=800",
                            Name = "Eyfel Kulesi",
                            Type = "Anıt"
                        },
                        new
                        {
                            Id = 4,
                            BudgetLevel = "Orta",
                            CityId = 2,
                            Description = "Mona Lisa başta olmak üzere binlerce tarihi esere ev sahipliği yapar.",
                            ImageUrl = "https://images.unsplash.com/photo-1543349689-9a4d426bee8e?auto=format&fit=crop&q=80&w=800",
                            Name = "Louvre Müzesi",
                            Type = "Müze"
                        },
                        new
                        {
                            Id = 5,
                            BudgetLevel = "Düşük",
                            CityId = 3,
                            Description = "Asakusa'da bulunan, Tokyo'nun en eski ve en ünlü Budist tapınağı.",
                            ImageUrl = "https://images.unsplash.com/photo-1563261775-80252b444766?auto=format&fit=crop&q=80&w=800",
                            Name = "Senso-ji Tapınağı",
                            Type = "Tapınak"
                        });
                });

            modelBuilder.Entity("GeziRehberi.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Gerçekten büyüleyici bir atmosfer.",
                            CreatedAt = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaceId = 1,
                            Rating = 5,
                            UserName = "Ahmet Y."
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Çok kalabalık ama kesinlikle görülmeli.",
                            CreatedAt = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaceId = 1,
                            Rating = 4,
                            UserName = "Maria S."
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Gece ışıklandırmasıyla harika görünüyor.",
                            CreatedAt = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaceId = 3,
                            Rating = 5,
                            UserName = "Canan B."
                        });
                });

            modelBuilder.Entity("GeziRehberi.Models.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredBudget")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("GeziRehberi.Models.Place", b =>
                {
                    b.HasOne("GeziRehberi.Models.City", "City")
                        .WithMany("Places")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("GeziRehberi.Models.Review", b =>
                {
                    b.HasOne("GeziRehberi.Models.Place", "Place")
                        .WithMany("Reviews")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("GeziRehberi.Models.City", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("GeziRehberi.Models.Place", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
